//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gostinica
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Гостиница.
    /// </summary>
    // *** Start programmer edit section *** (Гостиница CustomAttributes)

    // *** End programmer edit section *** (Гостиница CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГостиницаE", new string[] {
            "Наименование as \'Наименование\'",
            "ОПФ as \'ОПФ\'",
            "ОКПО as \'ОКПО\'"})]
    [View("ГостиницаL", new string[] {
            "Наименование as \'Наименование\'",
            "ОПФ as \'ОПФ\'",
            "ОКПО as \'ОКПО\'"})]
    public class Гостиница : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fОПФ;
        
        private string fОКПО;
        
        // *** Start programmer edit section *** (Гостиница CustomMembers)

        // *** End programmer edit section *** (Гостиница CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Гостиница.Наименование CustomAttributes)

        // *** End programmer edit section *** (Гостиница.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Гостиница.Наименование Get start)

                // *** End programmer edit section *** (Гостиница.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Гостиница.Наименование Get end)

                // *** End programmer edit section *** (Гостиница.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гостиница.Наименование Set start)

                // *** End programmer edit section *** (Гостиница.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Гостиница.Наименование Set end)

                // *** End programmer edit section *** (Гостиница.Наименование Set end)
            }
        }
        
        /// <summary>
        /// ОКПО.
        /// </summary>
        // *** Start programmer edit section *** (Гостиница.ОКПО CustomAttributes)

        // *** End programmer edit section *** (Гостиница.ОКПО CustomAttributes)
        [StrLen(255)]
        public virtual string ОКПО
        {
            get
            {
                // *** Start programmer edit section *** (Гостиница.ОКПО Get start)

                // *** End programmer edit section *** (Гостиница.ОКПО Get start)
                string result = this.fОКПО;
                // *** Start programmer edit section *** (Гостиница.ОКПО Get end)

                // *** End programmer edit section *** (Гостиница.ОКПО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гостиница.ОКПО Set start)

                // *** End programmer edit section *** (Гостиница.ОКПО Set start)
                this.fОКПО = value;
                // *** Start programmer edit section *** (Гостиница.ОКПО Set end)

                // *** End programmer edit section *** (Гостиница.ОКПО Set end)
            }
        }
        
        /// <summary>
        /// ОПФ.
        /// </summary>
        // *** Start programmer edit section *** (Гостиница.ОПФ CustomAttributes)

        // *** End programmer edit section *** (Гостиница.ОПФ CustomAttributes)
        [StrLen(255)]
        public virtual string ОПФ
        {
            get
            {
                // *** Start programmer edit section *** (Гостиница.ОПФ Get start)

                // *** End programmer edit section *** (Гостиница.ОПФ Get start)
                string result = this.fОПФ;
                // *** Start programmer edit section *** (Гостиница.ОПФ Get end)

                // *** End programmer edit section *** (Гостиница.ОПФ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гостиница.ОПФ Set start)

                // *** End programmer edit section *** (Гостиница.ОПФ Set start)
                this.fОПФ = value;
                // *** Start programmer edit section *** (Гостиница.ОПФ Set end)

                // *** End programmer edit section *** (Гостиница.ОПФ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГостиницаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостиницаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостиницаE", typeof(IIS.Gostinica.Гостиница));
                }
            }
            
            /// <summary>
            /// "ГостиницаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостиницаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостиницаL", typeof(IIS.Gostinica.Гостиница));
                }
            }
        }
    }
}
