//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gostinica
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должности.
    /// </summary>
    // *** Start programmer edit section *** (Должности CustomAttributes)

    // *** End programmer edit section *** (Должности CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностиE", new string[] {
            "Наименование as \'Наименование\'",
            "ШтатЕдиницы as \'Штат единицы\'",
            "Оклад as \'Оклад\'"})]
    [View("ДолжностиL", new string[] {
            "Наименование as \'Наименование\'",
            "ШтатЕдиницы as \'Штат единицы\'",
            "Оклад as \'Оклад\'"})]
    public class Должности : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private double fШтатЕдиницы;
        
        private double fОклад;
        
        // *** Start programmer edit section *** (Должности CustomMembers)

        // *** End programmer edit section *** (Должности CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Должности.Наименование CustomAttributes)

        // *** End programmer edit section *** (Должности.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Должности.Наименование Get start)

                // *** End programmer edit section *** (Должности.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Должности.Наименование Get end)

                // *** End programmer edit section *** (Должности.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.Наименование Set start)

                // *** End programmer edit section *** (Должности.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Должности.Наименование Set end)

                // *** End programmer edit section *** (Должности.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Оклад.
        /// </summary>
        // *** Start programmer edit section *** (Должности.Оклад CustomAttributes)

        // *** End programmer edit section *** (Должности.Оклад CustomAttributes)
        public virtual double Оклад
        {
            get
            {
                // *** Start programmer edit section *** (Должности.Оклад Get start)

                // *** End programmer edit section *** (Должности.Оклад Get start)
                double result = this.fОклад;
                // *** Start programmer edit section *** (Должности.Оклад Get end)

                // *** End programmer edit section *** (Должности.Оклад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.Оклад Set start)

                // *** End programmer edit section *** (Должности.Оклад Set start)
                this.fОклад = value;
                // *** Start programmer edit section *** (Должности.Оклад Set end)

                // *** End programmer edit section *** (Должности.Оклад Set end)
            }
        }
        
        /// <summary>
        /// ШтатЕдиницы.
        /// </summary>
        // *** Start programmer edit section *** (Должности.ШтатЕдиницы CustomAttributes)

        // *** End programmer edit section *** (Должности.ШтатЕдиницы CustomAttributes)
        public virtual double ШтатЕдиницы
        {
            get
            {
                // *** Start programmer edit section *** (Должности.ШтатЕдиницы Get start)

                // *** End programmer edit section *** (Должности.ШтатЕдиницы Get start)
                double result = this.fШтатЕдиницы;
                // *** Start programmer edit section *** (Должности.ШтатЕдиницы Get end)

                // *** End programmer edit section *** (Должности.ШтатЕдиницы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.ШтатЕдиницы Set start)

                // *** End programmer edit section *** (Должности.ШтатЕдиницы Set start)
                this.fШтатЕдиницы = value;
                // *** Start programmer edit section *** (Должности.ШтатЕдиницы Set end)

                // *** End programmer edit section *** (Должности.ШтатЕдиницы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностиE", typeof(IIS.Gostinica.Должности));
                }
            }
            
            /// <summary>
            /// "ДолжностиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностиL", typeof(IIS.Gostinica.Должности));
                }
            }
        }
    }
}
