//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gostinica
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Обяз сотр.
    /// </summary>
    // *** Start programmer edit section *** (ОбязСотр CustomAttributes)

    // *** End programmer edit section *** (ОбязСотр CustomAttributes)
    [AutoAltered()]
    [Caption("Обяз сотр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОбязСотрE", new string[] {
            "РегНомер as \'Рег номер\'",
            "Место as \'Место\'",
            "Дата as \'Дата\'",
            "Наименование as \'Наименование\'",
            "Гостиница as \'Гостиница\'",
            "Гостиница.Наименование as \'Наименование\'",
            "Персонал as \'Персонал\'",
            "Персонал.ФИО as \'ФИО\'",
            "ТЧОбязСотр as \'Т ч обяз сотр\'",
            "ТЧОбязСотр.Обязанности as \'Обязанности\'"}, Hidden=new string[] {
            "Гостиница.Наименование",
            "Персонал.ФИО",
            "ТЧОбязСотр.Обязанности"})]
    [MasterViewDefineAttribute("ОбязСотрE", "Гостиница", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОбязСотрE", "Персонал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ОбязСотрE", "ТЧОбязСотр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Обязанности")]
    [View("ОбязСотрL", new string[] {
            "РегНомер as \'Рег номер\'",
            "Место as \'Место\'",
            "Дата as \'Дата\'",
            "Наименование as \'Наименование\'",
            "Гостиница.Наименование as \'Наименование\'",
            "Персонал.ФИО as \'ФИО\'",
            "ТЧОбязСотр.Обязанности as \'Обязанности\'"})]
    public class ОбязСотр : ICSSoft.STORMNET.DataObject
    {
        
        private string fРегНомер;
        
        private string fМесто;
        
        private System.DateTime fДата;
        
        private string fНаименование;
        
        private IIS.Gostinica.Гостиница fГостиница;
        
        private IIS.Gostinica.Персонал fПерсонал;
        
        private IIS.Gostinica.ТЧОбязСотр fТЧОбязСотр;
        
        // *** Start programmer edit section *** (ОбязСотр CustomMembers)

        // *** End programmer edit section *** (ОбязСотр CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ОбязСотр.Дата CustomAttributes)

        // *** End programmer edit section *** (ОбязСотр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ОбязСотр.Дата Get start)

                // *** End programmer edit section *** (ОбязСотр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ОбязСотр.Дата Get end)

                // *** End programmer edit section *** (ОбязСотр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбязСотр.Дата Set start)

                // *** End programmer edit section *** (ОбязСотр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ОбязСотр.Дата Set end)

                // *** End programmer edit section *** (ОбязСотр.Дата Set end)
            }
        }
        
        /// <summary>
        /// Место.
        /// </summary>
        // *** Start programmer edit section *** (ОбязСотр.Место CustomAttributes)

        // *** End programmer edit section *** (ОбязСотр.Место CustomAttributes)
        [StrLen(255)]
        public virtual string Место
        {
            get
            {
                // *** Start programmer edit section *** (ОбязСотр.Место Get start)

                // *** End programmer edit section *** (ОбязСотр.Место Get start)
                string result = this.fМесто;
                // *** Start programmer edit section *** (ОбязСотр.Место Get end)

                // *** End programmer edit section *** (ОбязСотр.Место Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбязСотр.Место Set start)

                // *** End programmer edit section *** (ОбязСотр.Место Set start)
                this.fМесто = value;
                // *** Start programmer edit section *** (ОбязСотр.Место Set end)

                // *** End programmer edit section *** (ОбязСотр.Место Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ОбязСотр.Наименование CustomAttributes)

        // *** End programmer edit section *** (ОбязСотр.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ОбязСотр.Наименование Get start)

                // *** End programmer edit section *** (ОбязСотр.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ОбязСотр.Наименование Get end)

                // *** End programmer edit section *** (ОбязСотр.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбязСотр.Наименование Set start)

                // *** End programmer edit section *** (ОбязСотр.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ОбязСотр.Наименование Set end)

                // *** End programmer edit section *** (ОбязСотр.Наименование Set end)
            }
        }
        
        /// <summary>
        /// РегНомер.
        /// </summary>
        // *** Start programmer edit section *** (ОбязСотр.РегНомер CustomAttributes)

        // *** End programmer edit section *** (ОбязСотр.РегНомер CustomAttributes)
        [StrLen(255)]
        public virtual string РегНомер
        {
            get
            {
                // *** Start programmer edit section *** (ОбязСотр.РегНомер Get start)

                // *** End programmer edit section *** (ОбязСотр.РегНомер Get start)
                string result = this.fРегНомер;
                // *** Start programmer edit section *** (ОбязСотр.РегНомер Get end)

                // *** End programmer edit section *** (ОбязСотр.РегНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбязСотр.РегНомер Set start)

                // *** End programmer edit section *** (ОбязСотр.РегНомер Set start)
                this.fРегНомер = value;
                // *** Start programmer edit section *** (ОбязСотр.РегНомер Set end)

                // *** End programmer edit section *** (ОбязСотр.РегНомер Set end)
            }
        }
        
        /// <summary>
        /// Обяз сотр.
        /// </summary>
        // *** Start programmer edit section *** (ОбязСотр.Гостиница CustomAttributes)

        // *** End programmer edit section *** (ОбязСотр.Гостиница CustomAttributes)
        [PropertyStorage(new string[] {
                "Гостиница"})]
        [NotNull()]
        public virtual IIS.Gostinica.Гостиница Гостиница
        {
            get
            {
                // *** Start programmer edit section *** (ОбязСотр.Гостиница Get start)

                // *** End programmer edit section *** (ОбязСотр.Гостиница Get start)
                IIS.Gostinica.Гостиница result = this.fГостиница;
                // *** Start programmer edit section *** (ОбязСотр.Гостиница Get end)

                // *** End programmer edit section *** (ОбязСотр.Гостиница Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбязСотр.Гостиница Set start)

                // *** End programmer edit section *** (ОбязСотр.Гостиница Set start)
                this.fГостиница = value;
                // *** Start programmer edit section *** (ОбязСотр.Гостиница Set end)

                // *** End programmer edit section *** (ОбязСотр.Гостиница Set end)
            }
        }
        
        /// <summary>
        /// Обяз сотр.
        /// </summary>
        // *** Start programmer edit section *** (ОбязСотр.Персонал CustomAttributes)

        // *** End programmer edit section *** (ОбязСотр.Персонал CustomAttributes)
        [PropertyStorage(new string[] {
                "Персонал"})]
        [NotNull()]
        public virtual IIS.Gostinica.Персонал Персонал
        {
            get
            {
                // *** Start programmer edit section *** (ОбязСотр.Персонал Get start)

                // *** End programmer edit section *** (ОбязСотр.Персонал Get start)
                IIS.Gostinica.Персонал result = this.fПерсонал;
                // *** Start programmer edit section *** (ОбязСотр.Персонал Get end)

                // *** End programmer edit section *** (ОбязСотр.Персонал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбязСотр.Персонал Set start)

                // *** End programmer edit section *** (ОбязСотр.Персонал Set start)
                this.fПерсонал = value;
                // *** Start programmer edit section *** (ОбязСотр.Персонал Set end)

                // *** End programmer edit section *** (ОбязСотр.Персонал Set end)
            }
        }
        
        /// <summary>
        /// Обяз сотр.
        /// </summary>
        // *** Start programmer edit section *** (ОбязСотр.ТЧОбязСотр CustomAttributes)

        // *** End programmer edit section *** (ОбязСотр.ТЧОбязСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "ТЧОбязСотр"})]
        [NotNull()]
        public virtual IIS.Gostinica.ТЧОбязСотр ТЧОбязСотр
        {
            get
            {
                // *** Start programmer edit section *** (ОбязСотр.ТЧОбязСотр Get start)

                // *** End programmer edit section *** (ОбязСотр.ТЧОбязСотр Get start)
                IIS.Gostinica.ТЧОбязСотр result = this.fТЧОбязСотр;
                // *** Start programmer edit section *** (ОбязСотр.ТЧОбязСотр Get end)

                // *** End programmer edit section *** (ОбязСотр.ТЧОбязСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбязСотр.ТЧОбязСотр Set start)

                // *** End programmer edit section *** (ОбязСотр.ТЧОбязСотр Set start)
                this.fТЧОбязСотр = value;
                // *** Start programmer edit section *** (ОбязСотр.ТЧОбязСотр Set end)

                // *** End programmer edit section *** (ОбязСотр.ТЧОбязСотр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОбязСотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбязСотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбязСотрE", typeof(IIS.Gostinica.ОбязСотр));
                }
            }
            
            /// <summary>
            /// "ОбязСотрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбязСотрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбязСотрL", typeof(IIS.Gostinica.ОбязСотр));
                }
            }
        }
    }
}
