//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gostinica
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч обяз сотр.
    /// </summary>
    // *** Start programmer edit section *** (ТЧОбязСотр CustomAttributes)

    // *** End programmer edit section *** (ТЧОбязСотр CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч обяз сотр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧОбязСотрE", new string[] {
            "Номер as \'Номер\'",
            "Обязанности as \'Обязанности\'",
            "ДатаСост as \'Дата сост\'",
            "Должности as \'Должности\'",
            "Должности.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Должности.Наименование"})]
    [MasterViewDefineAttribute("ТЧОбязСотрE", "Должности", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ТЧОбязСотрL", new string[] {
            "Номер as \'Номер\'",
            "Обязанности as \'Обязанности\'",
            "ДатаСост as \'Дата сост\'",
            "Должности.Наименование as \'Наименование\'"})]
    public class ТЧОбязСотр : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fОбязанности;
        
        private System.DateTime fДатаСост;
        
        private IIS.Gostinica.Должности fДолжности;
        
        // *** Start programmer edit section *** (ТЧОбязСотр CustomMembers)

        // *** End programmer edit section *** (ТЧОбязСотр CustomMembers)

        
        /// <summary>
        /// ДатаСост.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОбязСотр.ДатаСост CustomAttributes)

        // *** End programmer edit section *** (ТЧОбязСотр.ДатаСост CustomAttributes)
        public virtual System.DateTime ДатаСост
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОбязСотр.ДатаСост Get start)

                // *** End programmer edit section *** (ТЧОбязСотр.ДатаСост Get start)
                System.DateTime result = this.fДатаСост;
                // *** Start programmer edit section *** (ТЧОбязСотр.ДатаСост Get end)

                // *** End programmer edit section *** (ТЧОбязСотр.ДатаСост Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОбязСотр.ДатаСост Set start)

                // *** End programmer edit section *** (ТЧОбязСотр.ДатаСост Set start)
                this.fДатаСост = value;
                // *** Start programmer edit section *** (ТЧОбязСотр.ДатаСост Set end)

                // *** End programmer edit section *** (ТЧОбязСотр.ДатаСост Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОбязСотр.Номер CustomAttributes)

        // *** End programmer edit section *** (ТЧОбязСотр.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОбязСотр.Номер Get start)

                // *** End programmer edit section *** (ТЧОбязСотр.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ТЧОбязСотр.Номер Get end)

                // *** End programmer edit section *** (ТЧОбязСотр.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОбязСотр.Номер Set start)

                // *** End programmer edit section *** (ТЧОбязСотр.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ТЧОбязСотр.Номер Set end)

                // *** End programmer edit section *** (ТЧОбязСотр.Номер Set end)
            }
        }
        
        /// <summary>
        /// Обязанности.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОбязСотр.Обязанности CustomAttributes)

        // *** End programmer edit section *** (ТЧОбязСотр.Обязанности CustomAttributes)
        [StrLen(255)]
        public virtual string Обязанности
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОбязСотр.Обязанности Get start)

                // *** End programmer edit section *** (ТЧОбязСотр.Обязанности Get start)
                string result = this.fОбязанности;
                // *** Start programmer edit section *** (ТЧОбязСотр.Обязанности Get end)

                // *** End programmer edit section *** (ТЧОбязСотр.Обязанности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОбязСотр.Обязанности Set start)

                // *** End programmer edit section *** (ТЧОбязСотр.Обязанности Set start)
                this.fОбязанности = value;
                // *** Start programmer edit section *** (ТЧОбязСотр.Обязанности Set end)

                // *** End programmer edit section *** (ТЧОбязСотр.Обязанности Set end)
            }
        }
        
        /// <summary>
        /// Т ч обяз сотр.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОбязСотр.Должности CustomAttributes)

        // *** End programmer edit section *** (ТЧОбязСотр.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.Gostinica.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОбязСотр.Должности Get start)

                // *** End programmer edit section *** (ТЧОбязСотр.Должности Get start)
                IIS.Gostinica.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (ТЧОбязСотр.Должности Get end)

                // *** End programmer edit section *** (ТЧОбязСотр.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОбязСотр.Должности Set start)

                // *** End programmer edit section *** (ТЧОбязСотр.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (ТЧОбязСотр.Должности Set end)

                // *** End programmer edit section *** (ТЧОбязСотр.Должности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧОбязСотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧОбязСотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧОбязСотрE", typeof(IIS.Gostinica.ТЧОбязСотр));
                }
            }
            
            /// <summary>
            /// "ТЧОбязСотрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧОбязСотрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧОбязСотрL", typeof(IIS.Gostinica.ТЧОбязСотр));
                }
            }
        }
    }
}
