//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gostinica
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч штат расп.
    /// </summary>
    // *** Start programmer edit section *** (ТЧШтатРасп CustomAttributes)

    // *** End programmer edit section *** (ТЧШтатРасп CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч штат расп")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧШтатРаспE", new string[] {
            "Надбавки as \'Надбавки\'",
            "Всего as \'Всего\'",
            "Дата as \'Дата\'",
            "Персонал as \'Персонал\'",
            "Персонал.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Персонал.ФИО"})]
    [MasterViewDefineAttribute("ТЧШтатРаспE", "Персонал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ТЧШтатРаспL", new string[] {
            "Надбавки as \'Надбавки\'",
            "Всего as \'Всего\'",
            "Дата as \'Дата\'",
            "Персонал.ФИО as \'ФИО\'"})]
    public class ТЧШтатРасп : ICSSoft.STORMNET.DataObject
    {
        
        private double fНадбавки;
        
        private double fВсего;
        
        private System.DateTime fДата;
        
        private IIS.Gostinica.Персонал fПерсонал;
        
        // *** Start programmer edit section *** (ТЧШтатРасп CustomMembers)

        // *** End programmer edit section *** (ТЧШтатРасп CustomMembers)

        
        /// <summary>
        /// Всего.
        /// </summary>
        // *** Start programmer edit section *** (ТЧШтатРасп.Всего CustomAttributes)

        // *** End programmer edit section *** (ТЧШтатРасп.Всего CustomAttributes)
        public virtual double Всего
        {
            get
            {
                // *** Start programmer edit section *** (ТЧШтатРасп.Всего Get start)

                // *** End programmer edit section *** (ТЧШтатРасп.Всего Get start)
                double result = this.fВсего;
                // *** Start programmer edit section *** (ТЧШтатРасп.Всего Get end)

                // *** End programmer edit section *** (ТЧШтатРасп.Всего Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧШтатРасп.Всего Set start)

                // *** End programmer edit section *** (ТЧШтатРасп.Всего Set start)
                this.fВсего = value;
                // *** Start programmer edit section *** (ТЧШтатРасп.Всего Set end)

                // *** End programmer edit section *** (ТЧШтатРасп.Всего Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ТЧШтатРасп.Дата CustomAttributes)

        // *** End programmer edit section *** (ТЧШтатРасп.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ТЧШтатРасп.Дата Get start)

                // *** End programmer edit section *** (ТЧШтатРасп.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ТЧШтатРасп.Дата Get end)

                // *** End programmer edit section *** (ТЧШтатРасп.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧШтатРасп.Дата Set start)

                // *** End programmer edit section *** (ТЧШтатРасп.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ТЧШтатРасп.Дата Set end)

                // *** End programmer edit section *** (ТЧШтатРасп.Дата Set end)
            }
        }
        
        /// <summary>
        /// Надбавки.
        /// </summary>
        // *** Start programmer edit section *** (ТЧШтатРасп.Надбавки CustomAttributes)

        // *** End programmer edit section *** (ТЧШтатРасп.Надбавки CustomAttributes)
        public virtual double Надбавки
        {
            get
            {
                // *** Start programmer edit section *** (ТЧШтатРасп.Надбавки Get start)

                // *** End programmer edit section *** (ТЧШтатРасп.Надбавки Get start)
                double result = this.fНадбавки;
                // *** Start programmer edit section *** (ТЧШтатРасп.Надбавки Get end)

                // *** End programmer edit section *** (ТЧШтатРасп.Надбавки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧШтатРасп.Надбавки Set start)

                // *** End programmer edit section *** (ТЧШтатРасп.Надбавки Set start)
                this.fНадбавки = value;
                // *** Start programmer edit section *** (ТЧШтатРасп.Надбавки Set end)

                // *** End programmer edit section *** (ТЧШтатРасп.Надбавки Set end)
            }
        }
        
        /// <summary>
        /// Т ч штат расп.
        /// </summary>
        // *** Start programmer edit section *** (ТЧШтатРасп.Персонал CustomAttributes)

        // *** End programmer edit section *** (ТЧШтатРасп.Персонал CustomAttributes)
        [PropertyStorage(new string[] {
                "Персонал"})]
        [NotNull()]
        public virtual IIS.Gostinica.Персонал Персонал
        {
            get
            {
                // *** Start programmer edit section *** (ТЧШтатРасп.Персонал Get start)

                // *** End programmer edit section *** (ТЧШтатРасп.Персонал Get start)
                IIS.Gostinica.Персонал result = this.fПерсонал;
                // *** Start programmer edit section *** (ТЧШтатРасп.Персонал Get end)

                // *** End programmer edit section *** (ТЧШтатРасп.Персонал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧШтатРасп.Персонал Set start)

                // *** End programmer edit section *** (ТЧШтатРасп.Персонал Set start)
                this.fПерсонал = value;
                // *** Start programmer edit section *** (ТЧШтатРасп.Персонал Set end)

                // *** End programmer edit section *** (ТЧШтатРасп.Персонал Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧШтатРаспE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧШтатРаспE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧШтатРаспE", typeof(IIS.Gostinica.ТЧШтатРасп));
                }
            }
            
            /// <summary>
            /// "ТЧШтатРаспL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧШтатРаспL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧШтатРаспL", typeof(IIS.Gostinica.ТЧШтатРасп));
                }
            }
        }
    }
}
